<?php

/**
 * This is the model base class for the table "cidade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cidade".
 *
 * Columns in table "cidade" available as properties of the model,
 * followed by relations of table "cidade" available as properties of the model.
 *
 * @property integer $idcidade
 * @property string $nome
 *
 * @property Cliente[] $clientes
 */
abstract class BaseCidade extends GxActiveRecord {



	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cidade';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cidade|Cidades', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('nome', 'length', 'max'=>100),
			array('nome', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcidade, nome', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clientes' => array(self::HAS_MANY, 'Cliente', 'idcidade'),
			'empreendimentos' => array(self::HAS_MANY, 'Empreendimento', 'idcidade'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcidade' => Yii::t('app', 'Idcidade'),
			'nome' => Yii::t('app', 'Nome'),
			'clientes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcidade', $this->idcidade);
		$criteria->compare('nome', $this->nome, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
