<?php

/**
 * This is the model base class for the table "indice".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Indice".
 *
 * Columns in table "indice" available as properties of the model,
 * followed by relations of table "indice" available as properties of the model.
 *
 * @property integer $idindice
 * @property string $nome
 * @property double $valor
 * @property string $ativo
 *
 * @property Imovel[] $imovels
 */
abstract class BaseIndice extends GxActiveRecord {



	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'indice';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Índice|Índices', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('valor', 'numerical'),
			array('idcliente', 'numerical', 'integerOnly'=>true),
			array('nome', 'length', 'max'=>100),
			array('ativo', 'length', 'max'=>1),
			array('nome, valor, idcliente, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idindice, nome, valor, idcliente, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'imovels' => array(self::HAS_MANY, 'Imovel', 'idindice'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idindice' => Yii::t('app', 'Idindice'),
			'nome' => Yii::t('app', 'Nome'),
			'valor' => Yii::t('app', 'Valor'),
			'ativo' => Yii::t('app', 'Ativo'),
			'imovels' => null,
			'idcliente' => Yii::t('app', 'Cliente'),
			
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idindice', $this->idindice);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('valor', $this->valor);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
