<?php

/**
 * This is the model base class for the table "plano".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Plano".
 *
 * Columns in table "plano" available as properties of the model,
 * followed by relations of table "plano" available as properties of the model.
 *
 * @property integer $idplano
 * @property string $nome
 * @property integer $posicao
 * @property double $valor
 * @property string $destaque
 * @property string $descricao
 * @property integer $limite_empreendimentos
 * @property integer $limite_imoveis
 * @property integer $limite_corretores
 * @property integer $limite_usuarios
 * @property string $ativo
 * @property double $valor_adicional_usuario
 * @property double $valor_adicional_empreendimento
 *
 * @property Cliente[] $clientes
 */
abstract class BasePlano extends GxActiveRecord {



	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'plano';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Plano|Planos', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('posicao, limite_empreendimentos, limite_imoveis, limite_corretores, limite_usuarios', 'numerical', 'integerOnly'=>true),
			array('valor, valor_adicional_usuario, valor_adicional_empreendimento', 'numerical'),
			array('nome', 'length', 'max'=>100),
			array('ativo', 'length', 'max'=>1),
			array('destaque, descricao', 'safe'),
			array('nome, posicao, valor, destaque, descricao, limite_empreendimentos, limite_imoveis, limite_corretores, limite_usuarios, ativo, valor_adicional_usuario, valor_adicional_empreendimento', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idplano, nome, posicao, valor, destaque, descricao, limite_empreendimentos, limite_imoveis, limite_corretores, limite_usuarios, ativo, valor_adicional_usuario, valor_adicional_empreendimento', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clientes' => array(self::HAS_MANY, 'Cliente', 'idplano'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idplano' => Yii::t('app', 'Idplano'),
			'nome' => Yii::t('app', 'Nome'),
			'posicao' => Yii::t('app', 'Posicao'),
			'valor' => Yii::t('app', 'Valor'),
			'destaque' => Yii::t('app', 'Destaque'),
			'descricao' => Yii::t('app', 'Descricao'),
			'limite_empreendimentos' => Yii::t('app', 'Limite Empreendimentos'),
			'limite_imoveis' => Yii::t('app', 'Limite Imoveis'),
			'limite_corretores' => Yii::t('app', 'Limite Corretores'),
			'limite_usuarios' => Yii::t('app', 'Limite Usuarios'),
			'ativo' => Yii::t('app', 'Ativo'),
			'valor_adicional_usuario' => Yii::t('app', 'Valor Adicional Usuario'),
			'valor_adicional_empreendimento' => Yii::t('app', 'Valor Adicional Empreendimento'),
			'clientes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idplano', $this->idplano);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('posicao', $this->posicao);
		$criteria->compare('valor', $this->valor);
		$criteria->compare('destaque', $this->destaque, true);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('limite_empreendimentos', $this->limite_empreendimentos);
		$criteria->compare('limite_imoveis', $this->limite_imoveis);
		$criteria->compare('limite_corretores', $this->limite_corretores);
		$criteria->compare('limite_usuarios', $this->limite_usuarios);
		$criteria->compare('ativo', $this->ativo, true);
		$criteria->compare('valor_adicional_usuario', $this->valor_adicional_usuario);
		$criteria->compare('valor_adicional_empreendimento', $this->valor_adicional_empreendimento);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
