<?php

/**
 * This is the model base class for the table "historico_reserva".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HistoricoReserva".
 *
 * Columns in table "historico_reserva" available as properties of the model,
 * followed by relations of table "historico_reserva" available as properties of the model.
 *
 * @property integer $idhistorico_reserva
 * @property string $data
 * @property integer $idimovel
 * @property integer $idcorretor
 * @property string $status_antigo
 * @property string $status_novo
 * @property string $ativo
 *
 * @property Corretor $corretor
 * @property Imovel $imovel
 */
abstract class BaseHistoricoReserva extends GxActiveRecord {



	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'historico_reserva';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Histórico de Reserva|Histórico de Reservas', $n);
	}

	public static function representingColumn() {
		return array('data');
	}

	public function rules() {
		return array(
			array('idimovel, idcorretor, idimovel_reserva, idcliente', 'numerical', 'integerOnly'=>true),
			array('status_antigo, status_novo, notificacao', 'length', 'max'=>100),
			array('ativo', 'length', 'max'=>1),
			array('data', 'safe'),
			array('data, idimovel, idcorretor, status_antigo, status_novo, ativo, idimovel_reserva, idcliente, notificacao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idhistorico_reserva, data, idimovel, idcorretor, status_antigo, status_novo, ativo, idimovel_reserva, idcliente, notificacao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'corretor' => array(self::BELONGS_TO, 'Corretor', 'idcorretor'),
			'imovel' => array(self::BELONGS_TO, 'Imovel', 'idimovel'),
			'reserva' => array(self::BELONGS_TO, 'ImovelReserva', 'idimovel_reserva'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idhistorico_reserva' => Yii::t('app', 'Idhistorico Reserva'),
			'data' => Yii::t('app', 'Data'),
			'idimovel' => null,
			'idcorretor' => null,
			'status_antigo' => Yii::t('app', 'Status Antigo'),
			'status_novo' => Yii::t('app', 'Status Novo'),
			'ativo' => Yii::t('app', 'Ativo'),
			'corretor' => null,
			'imovel' => null,
			'idcliente' => Yii::t('app', 'Cliente'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idhistorico_reserva', $this->idhistorico_reserva);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('idimovel', $this->idimovel);
		$criteria->compare('idcorretor', $this->idcorretor);
		$criteria->compare('status_antigo', $this->status_antigo, true);
		$criteria->compare('status_novo', $this->status_novo, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
