<?php

/**
 * This is the model base class for the table "destaque".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Destaque".
 *
 * Columns in table "destaque" available as properties of the model,
 * followed by relations of table "destaque" available as properties of the model.
 *
 * @property integer $iddestaque
 * @property string $data
 * @property string $data_entrada
 * @property string $data_saida
 * @property integer $idimovel
 * @property string $titulo
 * @property string $texto
 *
 * @property Imovel $imovel
 */
abstract class BaseDestaque extends GxActiveRecord {



	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'destaque';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Destaque|Destaques', $n);
	}

	public static function representingColumn() {
		return array('data');
	}

	public function rules() {
		return array(
			array('idimovel, idcliente', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>100),
			array('data, data_entrada, data_saida, texto', 'safe'),
			array('data, data_entrada, data_saida, idimovel, idcliente, titulo, texto', 'default', 'setOnEmpty' => true, 'value' => null),
			array('iddestaque, data, data_entrada, data_saida, idimovel, idcliente, titulo, texto', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'imovel' => array(self::BELONGS_TO, 'Imovel', 'idimovel'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'iddestaque' => Yii::t('app', 'Iddestaque'),
			'data' => Yii::t('app', 'Data'),
			'data_entrada' => Yii::t('app', 'Data Entrada'),
			'data_saida' => Yii::t('app', 'Data Saida'),
			'idimovel' => null,
			'titulo' => Yii::t('app', 'Titulo'),
			'texto' => Yii::t('app', 'Texto'),
			'imovel' => null,
			'idcliente' => Yii::t('app', 'Cliente'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('iddestaque', $this->iddestaque);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('data_entrada', $this->data_entrada, true);
		$criteria->compare('data_saida', $this->data_saida, true);
		$criteria->compare('idimovel', $this->idimovel);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('texto', $this->texto, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
