<?php

/**
 * This is the model base class for the table "bairro".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bairro".
 *
 * Columns in table "bairro" available as properties of the model,
 * followed by relations of table "bairro" available as properties of the model.
 *
 * @property integer $idbairro
 * @property string $nome
 * @property integer $idcidade
 * @property string $ativo
 *
 * @property Cidade $cidade
 * @property Empreendimento[] $empreendimentos
 */
abstract class BaseBairro extends GxActiveRecord {



	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'bairro';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Bairro|Bairros', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('idcidade, idcliente', 'numerical', 'integerOnly'=>true),
			array('nome', 'length', 'max'=>100),
			array('ativo', 'length', 'max'=>1),
			array('nome, idcidade, idcliente, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idbairro, nome, idcidade, idcliente, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cidade' => array(self::BELONGS_TO, 'Cidade', 'idcidade'),
			'empreendimentos' => array(self::HAS_MANY, 'Empreendimento', 'idbairro'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idbairro' => Yii::t('app', 'Idbairro'),
			'nome' => Yii::t('app', 'Nome'),
			'idcidade' => null,
			'ativo' => Yii::t('app', 'Ativo'),
			'cidade' => null,
			'empreendimentos' => null,
			'idcliente' => Yii::t('app', 'Cliente'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idbairro', $this->idbairro);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('idcidade', $this->idcidade);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
