<?php

/**
 * This is the model base class for the table "corretor_cliente".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CorretorCliente".
 *
 * Columns in table "corretor_cliente" available as properties of the model,
 * followed by relations of table "corretor_cliente" available as properties of the model.
 *
 * @property integer $idcorretor_cliente
 * @property integer $idcorretor
 * @property integer $idcliente
 * @property string $ativo
 *
 * @property Cliente $cliente
 * @property Corretor $corretor
 */
abstract class BaseCorretorCliente extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'corretor_cliente';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CorretorCliente|CorretorClientes', $n);
	}

	public static function representingColumn() {
		return array('ativo');
	}

	public function rules() {
		return array(
			array('idcorretor, idcliente', 'required'),
			array('idcorretor, idcliente', 'numerical', 'integerOnly'=>true),
			array('ativo', 'length', 'max'=>1),
			array('ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcorretor_cliente, idcorretor, idcliente, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cliente' => array(self::BELONGS_TO, 'Cliente', 'idcliente'),
			'corretor' => array(self::BELONGS_TO, 'Corretor', 'idcorretor'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcorretor_cliente' => Yii::t('app', 'Idcorretor Cliente'),
			'idcorretor' => null,
			'idcliente' => null,
			'ativo' => Yii::t('app', 'Ativo'),
			'cliente' => null,
			'corretor' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcorretor_cliente', $this->idcorretor_cliente);
		$criteria->compare('idcorretor', $this->idcorretor);
		$criteria->compare('idcliente', $this->idcliente);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}