<?php

/**
 * This is the model base class for the table "cliente".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cliente".
 *
 * Columns in table "cliente" available as properties of the model,
 * followed by relations of table "cliente" available as properties of the model.
 *
 * @property integer $idcliente
 * @property string $data_criacao
 * @property string $nome_fantasia
 * @property string $razao_social
 * @property string $cnpj
 * @property string $email
 * @property string $telefone
 * @property string $endereco
 * @property string $site
 * @property string $responsavel_nome
 * @property string $responsavel_email
 * @property string $responsavel_telefone
 * @property integer $idplano
 * @property string $titulo
 * @property string $url
 * @property string $logomarca
 * @property string $cor
 * @property string $notificacao_email
 * @property integer $duracao_reserva
 * @property integer $duracao_renovacao
 * @property integer $duracao_contrato
 * @property string $ativo
 * @property double $valor_plano
 * @property double $valor_adicional
 * @property double $valor_total
 *
 * @property Arquivo[] $arquivos
 * @property ArquivoCategoria[] $arquivoCategorias
 * @property Aviso[] $avisos
 * @property Bairro[] $bairros
 * @property Plano $plano
 * @property CorretorCliente[] $corretorClientes
 * @property Destaque[] $destaques
 * @property Empreendimento[] $empreendimentos
 * @property HistoricoReserva[] $historicoReservas
 * @property Imovel[] $imovels
 * @property ImovelFavorito[] $imovelFavoritos
 * @property ImovelReserva[] $imovelReservas
 * @property Indice[] $indices
 * @property UserCliente[] $userClientes
 */
abstract class BaseCliente extends GxActiveRecord {


    public $logomarca_delete;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cliente';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cliente|Clientes', $n);
	}

	public static function representingColumn() {
		return array('nome_fantasia', 'titulo');
	}

	public function rules() {
		return array(
			array('idplano', 'required'),
			array('idplano, duracao_reserva, duracao_renovacao, duracao_contrato', 'numerical', 'integerOnly'=>true),
			array('valor_plano, valor_adicional, valor_total', 'numerical'),
			array('nome_fantasia, razao_social, cnpj, email, telefone, site, responsavel_nome, responsavel_email, responsavel_telefone, titulo, url, cor, notificacao_email', 'length', 'max'=>100),
			array('logomarca', 'length', 'max'=>120),
			array('ativo', 'length', 'max'=>1),
			array('data_criacao, endereco', 'safe'),
			array('logomarca', 'file', 'types'=>'jpg,png', 'allowEmpty'=>true),
			array('logomarca_delete', 'length', 'max'=>1),
			array('data_criacao, nome_fantasia, razao_social, cnpj, email, telefone, endereco, site, responsavel_nome, responsavel_email, responsavel_telefone, titulo, url, logomarca, cor, notificacao_email, duracao_reserva, duracao_renovacao, duracao_contrato, ativo, valor_plano, valor_adicional, valor_total', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcliente, data_criacao, nome_fantasia, razao_social, cnpj, email, telefone, endereco, site, responsavel_nome, responsavel_email, responsavel_telefone, idplano, titulo, url, logomarca, cor, notificacao_email, duracao_reserva, duracao_renovacao, duracao_contrato, ativo, valor_plano, valor_adicional, valor_total', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'arquivos' => array(self::HAS_MANY, 'Arquivo', 'idcliente'),
			'arquivoCategorias' => array(self::HAS_MANY, 'ArquivoCategoria', 'idcliente'),
			'avisos' => array(self::HAS_MANY, 'Aviso', 'idcliente'),
			'bairros' => array(self::HAS_MANY, 'Bairro', 'idcliente'),
			'plano' => array(self::BELONGS_TO, 'Plano', 'idplano'),
			'corretorClientes' => array(self::HAS_MANY, 'CorretorCliente', 'idcliente'),
			'destaques' => array(self::HAS_MANY, 'Destaque', 'idcliente'),
			'empreendimentos' => array(self::HAS_MANY, 'Empreendimento', 'idcliente'),
			'historicoReservas' => array(self::HAS_MANY, 'HistoricoReserva', 'idcliente'),
			'imovels' => array(self::HAS_MANY, 'Imovel', 'idcliente'),
			'imovelFavoritos' => array(self::HAS_MANY, 'ImovelFavorito', 'idcliente'),
			'imovelReservas' => array(self::HAS_MANY, 'ImovelReserva', 'idcliente'),
			'indices' => array(self::HAS_MANY, 'Indice', 'idcliente'),
			'userClientes' => array(self::HAS_MANY, 'UserCliente', 'idcliente'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcliente' => Yii::t('app', 'Idcliente'),
			'data_criacao' => Yii::t('app', 'Data Criacao'),
			'nome_fantasia' => Yii::t('app', 'Nome Fantasia'),
			'razao_social' => Yii::t('app', 'Razao Social'),
			'cnpj' => Yii::t('app', 'Cnpj'),
			'email' => Yii::t('app', 'Email'),
			'telefone' => Yii::t('app', 'Telefone'),
			'endereco' => Yii::t('app', 'Endereco'),
			'site' => Yii::t('app', 'Site'),
			'responsavel_nome' => Yii::t('app', 'Responsavel Nome'),
			'responsavel_email' => Yii::t('app', 'Responsavel Email'),
			'responsavel_telefone' => Yii::t('app', 'Responsavel Telefone'),
			'idplano' => null,
			'titulo' => Yii::t('app', 'Titulo'),
			'url' => Yii::t('app', 'Url'),
			'logomarca' => Yii::t('app', 'Logomarca'),
			'cor' => Yii::t('app', 'Cor'),
			'notificacao_email' => Yii::t('app', 'Notificacao Email'),
			'duracao_reserva' => Yii::t('app', 'Duracao Reserva'),
			'duracao_renovacao' => Yii::t('app', 'Duracao Renovacao'),
			'duracao_contrato' => Yii::t('app', 'Duracao Contrato'),
			'ativo' => Yii::t('app', 'Ativo'),
			'valor_plano' => Yii::t('app', 'Valor Plano'),
			'valor_adicional' => Yii::t('app', 'Valor Adicional'),
			'valor_total' => Yii::t('app', 'Valor Total'),
			'arquivos' => null,
			'arquivoCategorias' => null,
			'avisos' => null,
			'bairros' => null,
			'plano' => null,
			'corretorClientes' => null,
			'destaques' => null,
			'empreendimentos' => null,
			'historicoReservas' => null,
			'imovels' => null,
			'imovelFavoritos' => null,
			'imovelReservas' => null,
			'indices' => null,
			'userClientes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcliente', $this->idcliente);
		$criteria->compare('data_criacao', $this->data_criacao, true);
		$criteria->compare('nome_fantasia', $this->nome_fantasia, true);
		$criteria->compare('razao_social', $this->razao_social, true);
		$criteria->compare('cnpj', $this->cnpj, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('telefone', $this->telefone, true);
		$criteria->compare('endereco', $this->endereco, true);
		$criteria->compare('site', $this->site, true);
		$criteria->compare('responsavel_nome', $this->responsavel_nome, true);
		$criteria->compare('responsavel_email', $this->responsavel_email, true);
		$criteria->compare('responsavel_telefone', $this->responsavel_telefone, true);
		$criteria->compare('idplano', $this->idplano);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('logomarca', $this->logomarca, true);
		$criteria->compare('cor', $this->cor, true);
		$criteria->compare('notificacao_email', $this->notificacao_email, true);
		$criteria->compare('duracao_reserva', $this->duracao_reserva);
		$criteria->compare('duracao_renovacao', $this->duracao_renovacao);
		$criteria->compare('duracao_contrato', $this->duracao_contrato);
		$criteria->compare('ativo', $this->ativo, true);
		$criteria->compare('valor_plano', $this->valor_plano);
		$criteria->compare('valor_adicional', $this->valor_adicional);
		$criteria->compare('valor_total', $this->valor_total);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
